apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19PU0U3MDlkYzJ3ZldQWHVQWGxRQHBhc3Npbi1ldmVudHMtZG8tdXNlci0xNjI4NzkxMi0wLmMuZGIub25kaWdpdGFsb2NlYW4uY29tOjI1MDYwL3Bhc3Npbj9zc2xtb2RlPXJlcXVpcmU=
